plugins {
    id 'org.gradle.toolchains.foojay-resolver-convention' version '1.0.0'
}

rootProject.name = 'complianceos-backend'

include 'interfaces:rest'
include 'agent:core'
include 'agent:api'
include 'compliance:api'
include 'compliance:core'
include 'compliance:jobs'
include 'internal'
include 'tenancy:core'
include 'scheduler:core'
include 'knowledge:core'
include 'connectors:core'