globalProperties:
  infra.mongodb.database: INFRA
  app.mongodb.database: AGENT_ENGINE
  infra.default-server.MONGO_SERVER: default
  infra.default-server.SQL_SERVER: default
  infra.default-server.VECTOR_SERVER: default
  infra.default-server.CLOUDSTORAGE_SERVER: default
  infra.default-server.ENCRYPTION_KEY: default
