apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "complianceos.infra-base.instance" . }}
  namespace: {{ include "complianceos.infra-base.namespace" . }}
  labels:
    {{- include "complianceos.infra-base.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "complianceos.infra-base.selectorLabels" . | nindent 6 }}
  policyTypes:
    - Ingress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: {{ include "complianceos.infra-base.appNamespace" . }}
      ports:
        - protocol: TCP
          port: 4566
