app-base:
  imagePullSecrets:
    - name: ocir-pull
  tier: mining
  minReadySeconds: 0
  preStopSleepSeconds: 0
  terminationGracePeriodSeconds: 10
  deploymentStrategy:
    type: Recreate
  replicas: 1
  resources:
    requests:
      cpu: "200m"
      memory: "350Mi"
    limits:
      cpu: "200m"
      memory: "350Mi"
  config:
    applicationProperties:
      quarkus.otel.service.name: complianceos-compliance
      quarkus.otel.sdk.disabled: "true"
      quarkus.grpc.server.use-separate-server: "false"
      quarkus.shutdown.timeout: 5S
