apiVersion: v1
kind: Service
metadata:
  name: {{ include "complianceos.infra-base.instance" . }}
  namespace: {{ include "complianceos.infra-base.namespace" . }}
  labels:
    {{- include "complianceos.infra-base.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "complianceos.infra-base.selectorLabels" . | nindent 4 }}
  ports:
    - name: postgres
      port: 5432
      targetPort: postgres
