apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "complianceos.app-base.applicationPropertiesConfigMapName" . }}
  namespace: {{ include "complianceos.app-base.namespace" . }}
  labels:
    {{- include "complianceos.app-base.labels" . | nindent 4 }}
data:
  application.properties: |-
    {{- $config := .Values.config | default dict }}
    {{- range $key, $value := $config.applicationProperties }}
    {{ $key }}={{ $value }}
    {{- end }}
