apiVersion: v2
name: complianceos-mongodb
description: MongoDB for Agent Engine
type: application
version: 0.1.0
appVersion: "7.0"
dependencies:
  - name: infra-base
    version: 0.1.0
    repository: "file://../infra-base"
